name: thinktank_apply
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  file_picker: ^9.0.2
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.7.0
  flutter_pdfview: ^1.4.0
  flutter_riverpod: ^2.6.1
  google_ml_kit: ^0.19.0
  image_picker: ^1.1.2
  pdf: ^3.11.3
  printing: ^5.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^2.5.8
  json_serializable: ^6.9.4
  riverpod_generator: ^2.6.4
  custom_lint: ^0.7.3

flutter:
  uses-material-design: true
