name: cosmoplay
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.6.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.4
  video_player: ^2.9.2
  flutter_common: 
    path: ../flutter_common
  get: ^4.6.6
  freezed_annotation: ^2.4.4
  equatable: ^2.0.7
  cached_network_image: ^3.4.1
  http: ^1.2.2
  json_annotation: ^4.9.0
  copy_with_extension: ^6.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_flavorizr: ^2.2.3
  flutter_launcher_icons: ^0.14.2
  freezed: ^2.5.7
  build_runner: ^2.4.14
  copy_with_extension_gen: ^6.0.0
  json_serializable: ^6.6.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

flavorizr:
  flavors:
    dev:
      app:
        name: '[dev] cosmoplay'
      android:
        applicationId: 'com.paulyswen.cosmoplay.dev'
        firebase:
          config: '.firebase/dev/google-services.json'
      ios:
        bundleId: 'com.paulyswen.cosmoplay.dev'
        firebase:
          config: '.firebase/dev/GoogleService-Info.plist'
    prod:
      app:
        name: 'cosmoplay'
      android:
        applicationId: 'com.paulyswen.cosmoplay'
        firebase:
          config: '.firebase/prod/google-services.json'
      ios:
        bundleId: 'com.paulyswen.cosmoplay'
        firebase:
          config: '.firebase/prod/GoogleService-Info.plist'